name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake SVG files
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Use a dedicated action to push ONLY to the output branch
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true  # This ensures only the latest files are kept
